# Compact UI style (menu style at the bottom)
style = "compact"

# Open Atuin automatically when pressing Up
enter_accept = true

search_mode = "fuzzy"

# Makes Up use what you already typed as the initial fuzzy search filter
filter_mode_shell_up_key_binding = "directory"

# Show detailed stats (duration, date, etc.)
show_preview = true
inline_height = 10
