# ==========================================================================
# HYPRLOCK CONFIG GENERATED (MATUGEN - DARK THEME)
# DON'T TOUCH THIS FILE
# ==========================================================================

background {
    monitor =
    color = {{colors.surface.default.rgb}}
}

label { # Time
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 90
    font_family = sans-serif
    color = {{colors.on_background.default.rgb}}
    position = 0, 160
    halign = center
    valign = center
}

label { # Date
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    font_size = 20
    font_family = sans-serif
    color = {{colors.secondary.default.rgb}}
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = {{colors.primary.default.rgb}}
    inner_color = rgba({{colors.surface_container.default.hex_stripped}}dd)
    font_color = {{colors.on_background.default.rgb}}
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = {{colors.primary.default.rgb}}
    fail_color = {{colors.error.default.rgb}}
    fail_text = <i>$FAIL</i>
    position = 0, -80
    halign = center
    valign = center
}
